<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  	<modelVersion>4.0.0</modelVersion>
  	<groupId>SASS</groupId>
  	<artifactId>AV-LAB</artifactId>
  	<version>1.1.0-SNAPSHOT</version>
  	<packaging>jar</packaging>
	
	<!-- Hereda configuración y versiones gestionadas de Spring Boot -->
 	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.5</version>
		<relativePath/>
	</parent>
	
	<dependencies>
	
		<!-- Spring Boot Starter Thymeleaf: motor de plantillas HTML -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		
		<!-- Spring Boot Starter Web: Spring MVC, Tomcat embebido y JSON -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<!-- Dependencias para pruebas unitarias e integración -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		 <!-- JUnit para Surefire -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        
        <!-- Spring Boot Starter Data JPA: Hibernate + JPA -->
        <dependency>
    		<groupId>org.springframework.boot</groupId>
   			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		
		<!-- Apache Derby: motor de base de datos embebido -->
		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derby</artifactId>
		</dependency>
		
		<!-- Derbytools: herramientas y utilidades de Derby -->
		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derbytools</artifactId>
		</dependency>
		
	</dependencies>
	
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>

        <plugins>
            <!-- Configura Maven para procesar recursos en UTF-8 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <!-- Spring Boot Maven Plugin -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
    			<groupId>org.apache.maven.plugins</groupId>
    			<artifactId>maven-site-plugin</artifactId>
    			<version>3.12.1</version>
			</plugin>
        </plugins>
    </build>
    
   
    <!-- Surefire Report Plugin -->
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <skipEmptyReport>false</skipEmptyReport>
                </configuration>
            </plugin>
            <plugin>
    			<groupId>org.apache.maven.plugins</groupId>
    			<artifactId>maven-project-info-reports-plugin</artifactId>
    			<version>3.4.5</version>
			</plugin>
        </plugins>
    </reporting>

</project>