server.port=8081

spring.datasource.url=jdbc:derby:database;create=true
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.username=derbyuser
spring.datasource.password=password
spring.jackson.serialization.indent-output=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
derby.stream.error.file=log/derby.log