#spring.application.name=library
# Puerto del servidor
server.port=8081

spring.datasource.url=jdbc:derby:database;create=true
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.username=derbyuser
spring.datasource.password=password
#preserva los datos entre ejecuciones, la base de datos no es reseteada.
spring.jpa.hibernate.ddl-auto=update
#muestra en consola codigo SQL de forma indentada
spring.jackson.serialization.indent-output=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyTenSevenDialect

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
